attributes:
  # Show only if vCenter used
  metadata:
    restrictions:
      - condition: "settings:common.use_vcenter.value == false or not ( cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        action: "hide"
      - condition: "settings:neutron_advanced_configuration.neutron_dvr.value == true"
        message: "VMware DVS ML2 plugin does not support DVR feature. Keep Neutron DVR checkbox at unchecked state."
    group: 'network'
  vmware_dvs_fw_driver:
    value: true
    label: "Use the VMware DVS firewall driver"
    weight: 20
    type: "checkbox"
  vmware_dvs_net_maps:
    value: ""
    label: "Enter the Cluster to dvSwitch mapping."
    description: "List of ClusterName:dvSwitchName pairs, separated by semicolon."
    weight: 25
    type: "textarea"
    regex:
      source: &non_empty_string '\S'
      error: "Empty name of dvSwitch"
